config/routes.rb
Rails.application.routes.draw do

  # Authentication
  #----------------------------------------------------------------------

  scope module: :authentication do
    get :login, to: "sessions#new", as: :login
    post :login, to: "sessions#create", as: :authenticate
    get :logout, to: "sessions#destroy", as: :logout

    resources :password_resets, only: [:new, :create, :show, :update]
    resources :confirmations
  end

  # RSVP
  #----------------------------------------------------------------------

  resources :rsvp, only: [:index, :create, :show, :update], param: :rsvp_code do
    get :thanks, on: :member
  end

  # Standard
  #----------------------------------------------------------------------

  scope module: :authenticated do
    resource :dashboard

    resources :parties, param: :uuid do
      resources :guests, param: :uuid
    end

    resources :missing_mailing_addresses, only: [:index, :update], param: :uuid
    resources :save_the_dates, only: [:index, :update], param: :uuid
    resources :invitations, only: [:index, :update], param: :uuid

    resources :users
  end

  # Root
  #----------------------------------------------------------------------

  root to: "authentication/sessions#new"
end

app/models/guest.rb
class Guest < ApplicationRecord

  # Scopes
  #----------------------------------------------------------------------

  scope :alphabetical, -> { order(:first_name, :last_name) }
  scope :attending, -> { where(attending: true) }
  scope :not_attending, -> { where(attending: false) }
  scope :not_rsvped, -> { where(attending: nil) }

  # Macros
  #----------------------------------------------------------------------

  delegate :name, to: :party, prefix: true, allow_nil: true

  # Associations
  #----------------------------------------------------------------------

  belongs_to :account
  belongs_to :party

  has_many :alcoholic_beverages, through: :drinkings
  has_many :drinkings

  # Validations
  #----------------------------------------------------------------------

  validates :first_name, presence: true

  # Methods
  #----------------------------------------------------------------------

  def initials
    "#{first_name.first}#{last_name.first}".upcase
  end

  def first_and_last_name
    [first_name, last_name].join(" ")
  end

  def last_and_first_name
    [last_name, first_name].join(", ")
  end

  def alcoholic_beverage_names
    @alcoholic_beverage_names ||= generate_alcoholic_beverage_names
  end

  private

  def generate_alcoholic_beverage_names
    alcoholic_beverages.pluck(:name).map { |d| d.capitalize }.join(", ")
  end
end

app/controllers/authenticated/base_controller.rb
#======================================================================
# Parent for any controllers that require an authenticated user.
#======================================================================
module Authenticated
  class BaseController < ::ApplicationController
    layout "application"
    before_action :require_user

    def current_user
      if cookies[:user_authentication_token]
        @current_user ||= User.includes(:account).find_by(authentication_token: cookies[:user_authentication_token])
      end
    end
    helper_method :current_user

    def current_account
      if current_user
        @current_account ||= current_user.account
      end
    end
    helper_method :current_account

    private

    def require_user
      destroy_session_for_user("Must login before continuing") unless current_user.present?
    end

    def require_account_owner
      destroy_session_for_user("Account Owner required for that action") unless current_user.present? && current_user.account_owner?
    end
  end
end

app/controllers/authenticated/dashboards_controller.rb
module Authenticated
  class DashboardsController < BaseController
    before_action :set_page_title

    def show
      @attending = current_account.guests.attending.alphabetical.includes(:party)
      @not_attending = current_account.guests.not_attending.alphabetical.includes(:party)
      @not_rsvped = current_account.guests.not_rsvped.alphabetical.includes(:party)
    end

    private

    def set_page_title
      @page_title = "Dashboard"
    end
  end
end

app/controllers/authenticated/guests_controller.rb
module Authenticated
  class GuestsController < BaseController
    def index
      # @parties = current_account.parties.includes(:guests).alphabetical
      # @guests = current_account.guests.includes(:party).alphabetical
    end

    def new
      @party = get_party
      @guest = @party.guests.new
    end

    def create
      @party = get_party
      @guest = @party.guests.new(guest_params)
      if @guest.save
        flash[:notice] = "Guest created"
        redirect_to new_party_guest_path(@party.uuid)
      else
        flash[:error] = "Problem adding Guest"
        render :new
      end
    end

    def show
      @party = get_party
      @guest = get_guest
    end

    def edit
      @party = get_party
      @guest = get_guest
    end

    def update
      @party = get_party
      @guest = get_guest
      if @guest.update_attributes(guest_params)
        flash[:notice] = "Updated Guest"
        redirect_to party_path(@party.uuid)
      else
        flash[:error] = "Problem updating Guest"
        render :edit
      end
    end

    def destroy
      @party = get_party
      @guest = get_guest

      if @guest.destroy
        flash[:notice] = "Removed Guest"
        redirect_to party_path(@party.uuid)
      else
        flash[:error] = "Problem deleting Guest"
        render :show
      end
    end

    private

    def guest_params
      params.require(:guest).permit(
        :first_name,
        :last_name,
        :notes,
        :attending,
        alcoholic_beverage_ids: []
      ).merge(account: current_account)
    end

    def get_party
      @party ||= current_account.parties.find_by(uuid: params[:party_uuid])
    end

    def get_guest
      @guest ||= get_party.guests.find_by(uuid: params[:uuid])
    end
  end
end

app/controllers/authenticated/invitations_controller.rb
module Authenticated
  class InvitationsController < BaseController
    before_action :set_page_title

    def index
      @parties = current_account.parties.invitation_not_sent.alphabetical.group_by { |p| p.name.first.upcase }
    end

    def update
      @party = get_party
      if @party.update_attributes(party_params)
        flash.now[:notice] = "Updated Party"
      else
        # NOOP
      end
    end

    private

    def get_party
      current_account.parties.find_by(uuid: params[:uuid])
    end

    def party_params
      params.require(:party).permit(
        :invitation_sent
      )
    end

    def set_page_title
      @page_title = "Invitations not Sent"
    end
  end
end

app/controllers/authenticated/mailing_addresses_controller.rb
module Authenticated
  class MailingAddressesController < BaseController
    def index
      @parties = current_account.parties.missing_mailing_address.alphabetical.group_by { |p| p.name.first.upcase }
    end

    def update
      @party = get_party
      if @party.update_attributes(party_params)
        flash.now[:notice] = "Updated Mailing Address"
      else
        # NOOP
      end
    end

    private

    def get_party
      current_account.parties.find_by(uuid: params[:uuid])
    end

    def party_params
      params.require(:party).permit(
        :mailing_address
      )
    end
  end
end

app/controllers/authenticated/missing_mailing_addresses_controller.rb
module Authenticated
  class MissingMailingAddressesController < BaseController
    before_action :set_page_title

    def index
      @parties = current_account.parties.missing_mailing_address.alphabetical.group_by { |p| p.name.first.upcase }
    end

    def update
      @party = get_party
      if @party.update_attributes(party_params)
        flash.now[:notice] = "Updated Mailing Address"
      else
        # NOOP
      end
    end

    private

    def get_party
      current_account.parties.find_by(uuid: params[:uuid])
    end

    def party_params
      params.require(:party).permit(
        :mailing_address
      )
    end

    def set_page_title
      @page_title = "Missing Addresses"
    end
  end
end

app/controllers/authenticated/parties_controller.rb
module Authenticated
  class PartiesController < BaseController
    def index
      @parties = current_account.parties.includes(:guests).alphabetical.group_by { |p| p.name.first.upcase }
    end

    def new
      @party = current_account.parties.new
      3.times { @party.guests.build }
      @guests = @party.guests
    end

    def build_guest
    end

    def create
      @party = current_account.parties.new(party_params)
      if @party.save
        flash[:notice] = "Created Party"
        redirect_to new_party_guest_path(@party.uuid)
      else
        flash[:error] = "Problem adding Party"
        render :new
      end
    end

    def show
      @party = get_party
    end

    def edit
      @party = get_party
      @guests = @party.guests.alphabetical
    end

    def update
      @party = get_party

      respond_to do |format|
        if @party.update_attributes(party_params)
          format.html { redirect_to party_path(@party.uuid), notice: "Updated Party" }
          format.js { flash.now[:notice] = "Updated Party" }
        else
          format.html do
            flash[:error] = "Problem updating Party"
            render :edit
          end
          format.js { flash.now[:error] = "Problem updating Party" }
        end
      end
    end

    def destroy
      @party = get_party

      if @party.destroy
        flash[:notice] = "Removed Party"
        redirect_to parties_path
      else
        flash[:error] = "Problem deleting Party"
        render :show
      end
    end

    private

    def party_params
      params.require(:party).permit(
        :name,
        :save_the_date_sent,
        :invitation_sent,
        :mailing_address,
        :address1,
        :address2,
        :city,
        :state,
        :zip,
        guests_attributes: [:id, :first_name, :last_name, alcoholic_beverage_ids: []]
      )
    end

    def get_party
      current_account.parties.find_by(uuid: params[:uuid])
    end
  end
end

app/controllers/authenticated/save_the_dates_controller.rb
module Authenticated
  class SaveTheDatesController < BaseController
    before_action :set_page_title

    def index
      @parties = current_account.parties.save_the_date_not_sent.alphabetical.group_by { |p| p.name.first.upcase }
    end

    def update
      @party = get_party
      if @party.update_attributes(party_params)
        flash.now[:notice] = "Updated Party"
      else
        # NOOP
      end
    end

    private

    def get_party
      current_account.parties.find_by(uuid: params[:uuid])
    end

    def party_params
      params.require(:party).permit(
        :save_the_date_sent
      )
    end

    def set_page_title
      @page_title = "Save the Dates not Sent"
    end
  end
end

app/controllers/authenticated/users_controller.rb
module Authenticated
  class UsersController < BaseController
    before_action :require_account_owner, except: [:index, :show]

    def index
      @invited_users = current_account.users.unconfirmed.alphabetical
      @users = current_account.users.confirmed.alphabetical
    end

    def new
      @user = current_account.users.new
    end

    def create
      @user = ::Users::AsInvitation.new(invitation_params.merge(account: current_account))
      if @user.save
        flash[:notice] = "Invitation sent"
        redirect_to users_path
      else
        flash[:error] = "Problem inviting user"
        render :new
      end
    end

    def show
      @user = get_user
    end

    def edit
      @user = get_user
    end

    def update
      @user = get_user
      if @user.update_attributes(user_params)
        flash[:notice] = "Updated User"
        redirect_to user_path(@user.uuid)
      else
        flash[:error] = "Problem updating User"
        render :edit
      end
    end

    def destroy
      @user = get_user

      if @user.account_owner?
        flash[:error] = "Cannot remove Account Owner"
        redirect_to users_path
      else
        if @user.destroy
          flash[:notice] = "Removed User"
          redirect_to users_path
        else
          flash[:error] = "Problem deleting User"
          render :show
        end
      end
    end

    private

    def invitation_params
      params.require(:user).permit(
        :full_name,
        :email
      )
    end

    def user_params
      params.require(:user).permit(
        :email,
        :full_name
      )
    end

    def get_user
      current_account.users.find_by(uuid: params[:id])
    end
  end
end

app/views/authenticated/guests/_blank_state.html.erb
<div class="blank-state-container">
  <div class="blank-state">
    <div class="blank-state-primary">
      No Parties/Guests Yet
      <div class="blank-state-primary-subtext">
        A Part is a group of associated Guests that
        usually share the same mailing address.
      </div>
    </div>
    <div class="blank-state-actions">
      <%= link_to "Add Your First Party", new_party_path, class: "button button-raised-green" %>
    </div>
  </div>
</div>

app/views/authenticated/guests/_destroy_confirm_template.html.erb
<script id="guest-confirm-dialog-template" type="text/x-handlebars-template">
  <header>
    <div class="dialog-title">Remove Guest?</div>
  </header>
  <div class="dialog-content">
    Do you want to <strong class="color-red">completely</strong> remove this Guest?

    <ul class="helper-text">
      <li>Will be removed from any Party</li>
      <li>All the Guest's data will be removed</li>
    </ul>
  </div>
  <div class="dialog-actions align-right">
    <button type="button" class="button button-flat-grey" role="cancel">Cancel</button>
    <button type="button" class="button button-flat-red" role="confirm">Remove</button>
  </div>
</script>

app/views/authenticated/guests/_fields.html.erb
<div class="field field-xsmall field-responsive field-with-validations">
  <div class="field-label">
    <%= f.label :first_name, class: "required" %>
  </div>
  <div class="field-element">
    <%= f.text_field :first_name, required: true, autofocus: true, class: "full-width" %>
  </div>
</div>
<div class="field field-xsmall field-responsive field-with-validations">
  <div class="field-label">
    <%= f.label :last_name %>
  </div>
  <div class="field-element">
    <%= f.text_field :last_name, class: "full-width" %>
  </div>
</div>
<div class="field field-xsmall field-responsive">
  <div class="field-label">
    <%= f.label :alcoholic_beverages %>
  </div>
  <div class="field-element">
    <div class="toggle-container toggle-primary">
      <!-- Had to generate manually because automated approaches would not respect .toggle:last-child style -->
      <% AlcoholicBeverage.alphabetical.each do |b| %>
        <div class="toggle">
          <%= check_box_tag "guest[alcoholic_beverage_ids][]", b.id, @guest.alcoholic_beverage_ids.include?(b.id), { id: "guest_alcoholic_beverage_ids_#{b.id}" } %>
          <label for="guest_alcoholic_beverage_ids_<%= b.id %>"><%= b.name.capitalize %></label>
        </div>
      <% end %>
    </div>
    <%= hidden_field_tag "guest[alcoholic_beverage_ids][]" %>
    <div class="helper-text helper-text-bottom">
      Check all that apply
    </div>
  </div>
</div>
<div class="field field-xsmall field-responsive">
  <div class="field-label">
    <%= f.label :notes %>
  </div>
  <div class="field-element">
    <%= f.text_area :notes, class: "full-width", rows: 2 %>
  </div>
</div>

<hr class="spacer normal" />

<div class="field field-xsmall">
  <div class="field-title">
    RSVP Information
    <div class="field-subtitle">
      Provided by Guests when they RSVP
    </div>
  </div>
</div>
<div class="field field-xsmall field-responsive">
  <div class="field-label">
    <%= f.label :attending %>
  </div>
  <div class="field-element">
    <div class="segmented-control-container">
      <div class="segmented-control segmented-control-primary">
        <%= f.radio_button :attending, true %>
        <%= f.label :attending_true, "Accepts with Pleasure" %>
      </div>
      <div class="segmented-control segmented-control-secondary">
        <%= f.radio_button :attending, false %>
        <%= f.label :attending_false, "Declines with Regret" %>
      </div>
    </div>
  </div>
</div>
<div class="field field-xsmall field-responsive">
  <div class="field-label">
    <%= f.label :rsvp_notes, "RSVP Notes" %>
    <div class="helper-text">
      (Only Guests may change)
    </div>
  </div>
  <div class="field-element">
    <%= f.text_area :rsvp_notes, class: "full-width disabled", rows: 2 %>
  </div>
</div>

app/views/authenticated/guests/_guest.html.erb
<div class="list-item" role="guest">
  <div class="list-item-primary">
    <%= guest.first_and_last_name %>
    <div class="list-item-primary-subtext">
      <%= guest.alcoholic_beverage_names %>
    </div>
  </div>
  <div class="list-item-secondary">
    <%= link_to "edit", edit_party_guest_path(@party.uuid, guest.uuid), class: "material-icons button-icon" %>
    <%= link_to "delete", party_guest_path(@party.uuid, guest.uuid), class: "material-icons button-icon", method: "DELETE", data: { "custom-confirm" => { template: "guest-confirm-dialog-template" } } %>
  </div>
</div>

app/views/authenticated/guests/edit.html.erb
<% content_for(:appbar_nav_icon) { up_button(party_path(@party.uuid)) } %>
<% content_for(:appbar_title) { "Edit Guest" } %>
<% content_for(:appbar_actions) do %>
  <%= button_tag "Update", class: "button button-raised-white", data: { submit: "#guest-form" } %>
<% end %>

<%= form_for @guest, url: party_guest_path(@party.uuid, @guest.uuid), html: { id: "guest-form" } do |f| %>
<div class="card constrained-medium">
  <div class="card-header">
    <div class="card-header-primary">
      <%= @party.name %>
      <div class="card-header-primary-subtext">
        <%= pluralize @party.guests.count, "guest" %>
      </div>
    </div>
  </div>
  <div class="card-content">
    <%= render "authenticated/guests/fields", f: f %>
  </div>
  <div class="card-actions">
    <%= f.submit "Update", class: "button button-raised-primary", id: "update-guest-button" %>
    <%= link_to "Cancel", party_path(@party.uuid), class: "button button-flat-grey" %>
  </div>
</div>
<% end %>

app/views/authenticated/guests/index.html.erb
<% content_for(:appbar_title) { "Guests" } %>
<% content_for(:appbar_actions) do %>
  <%= link_to "group_add", new_party_path, class: "material-icons appbar-button", id: "new-guest-button", data: { "tooltip-position": "bottom-left", tooltip: "New Party" } %>
<% end %>
<%= link_to new_party_path, class: "button fab fab-secondary", id: "new-guest-fab", data: { "tooltip-position": "left", tooltip: "New Party" }, role: "fab" do %>
  <i class="material-icons">group_add</i>
<% end %>

<% if false #@parties.any? %>
  <div class="list-subheader">
    A Guest is an individual person
  </div>
  <div class="list list-bordered list-one-lines list-divided list-hoverable rounded-corners background-color-white allow-room-for-fab-at-bottom" id="guests">
    <%#= render @guests %>
  </div>
<% else %>
  <%= render "authenticated/guests/blank_state" %>
<% end %>

app/views/authenticated/guests/new.html.erb
<% content_for(:appbar_nav_icon) { up_button(party_path(@party.uuid)) } %>
<% content_for(:appbar_title) do %>
  <%= @party.name %>
  <div class="appbar-subtitle">
    New Guest
  </div>
<% end %>
<% content_for(:appbar_actions) do %>
  <%= button_tag "Create", class: "button button-raised-white", data: { submit: "#guest-form" } %>
<% end %>

<%= form_for @guest, url: party_guests_path(@party.uuid), html: { id: "guest-form" } do |f| %>
  <div class="card constrained-medium">
    <div class="card-header">
      <div class="card-header-primary">
        <%= @party.name %>
        <div class="card-header-primary-subtext">
          <%= pluralize @party.guests.count, "guest" %>
        </div>
      </div>
    </div>
    <div class="card-content">
      <%= render "authenticated/guests/fields", f: f %>
    </div>
    <div class="card-actions">
      <%= f.submit "Create", class: "button button-raised-primary", id: "create-guest-button" %>
      <%= link_to "Cancel", party_path(@party.uuid), class: "button button-flat-grey" %>
      <%= link_to "group_add", new_party_path, class: "material-icons button-icon float-right", title: "New Party" %>
    </div>
  </div>
<% end %>

app/views/authenticated/guests/show.html.erb
<% content_for(:appbar_nav_icon) do %>
  <%= link_to "", attendees_path, class: "zmdi zmdi-arrow-left appbar-button" %>
<% end %>
<% content_for(:appbar_title) { "Attendee" } %>
<% content_for(:appbar_actions) do %>
  <%= link_to "", edit_attendee_path(@attendee.uuid), class: "zmdi zmdi-edit appbar-button", data: { tooltip: "Edit" } %>
  <%= link_to "", attendee_path(@attendee.uuid), class: "zmdi zmdi-delete appbar-button", method: "DELETE", data: { "custom-confirm" => { template: "attendee-confirm-dialog-template" }, tooltip: "Delete" } %>
  <span class="appbar-divider"></span>
<% end %>

<div class="card full-width constrained-medium">
  <div class="card-header">
    <div class="card-header-title">
      <%= @attendee.full_name %>
    </div>
  </div>
</div>

<%= render "authenticated/attendees/destroy_confirm_template" %>