config/routes.rb
Rails.application.routes.draw do

  # Authentication
  #----------------------------------------------------------------------

  scope module: :authentication do
    get :login, to: "sessions#new", as: :login
    post :login, to: "sessions#create", as: :authenticate
    get :logout, to: "sessions#destroy", as: :logout

    resources :password_resets, only: [:new, :create, :show, :update]
    resources :confirmations
  end

  # RSVP
  #----------------------------------------------------------------------

  resources :rsvp, only: [:index, :create, :show, :update], param: :rsvp_code do
    get :thanks, on: :member
  end

  # Standard
  #----------------------------------------------------------------------

  scope module: :authenticated do
    resource :dashboard

    resources :parties, param: :uuid do
      resources :guests, param: :uuid
    end

    resources :missing_mailing_addresses, only: [:index, :update], param: :uuid
    resources :save_the_dates, only: [:index, :update], param: :uuid
    resources :invitations, only: [:index, :update], param: :uuid

    resources :users
  end

  # Root
  #----------------------------------------------------------------------

  root to: "authentication/sessions#new"
end

app/models/guest.rb
class Guest < ApplicationRecord

  # Scopes
  #----------------------------------------------------------------------

  scope :alphabetical, -> { order(:first_name, :last_name) }
  scope :attending, -> { where(attending: true) }
  scope :not_attending, -> { where(attending: false) }
  scope :not_rsvped, -> { where(attending: nil) }

  # Macros
  #----------------------------------------------------------------------

  delegate :name, to: :party, prefix: true, allow_nil: true

  # Associations
  #----------------------------------------------------------------------

  belongs_to :account
  belongs_to :party

  has_many :alcoholic_beverages, through: :drinkings
  has_many :drinkings

  # Validations
  #----------------------------------------------------------------------

  validates :first_name, presence: true

  # Methods
  #----------------------------------------------------------------------

  def initials
    "#{first_name.first}#{last_name.first}".upcase
  end

  def first_and_last_name
    [first_name, last_name].join(" ")
  end

  def last_and_first_name
    [last_name, first_name].join(", ")
  end

  def alcoholic_beverage_names
    @alcoholic_beverage_names ||= generate_alcoholic_beverage_names
  end

  private

  def generate_alcoholic_beverage_names
    alcoholic_beverages.pluck(:name).map { |d| d.capitalize }.join(", ")
  end
end

app/models/party.rb
class Party < ApplicationRecord

  # Scopes
  #----------------------------------------------------------------------

  scope :alphabetical, -> { order(:name) }
  scope :missing_mailing_address, -> { where(mailing_address: [nil, ""]) }
  scope :save_the_date_not_sent, -> { where(save_the_date_sent: [false, nil]) }
  scope :invitation_not_sent, -> { where(invitation_sent: [false, nil]) }

  # Macros
  #----------------------------------------------------------------------

  before_save :append_party_to_name

  # Associations
  #----------------------------------------------------------------------

  belongs_to :account
  has_many :guests, dependent: :destroy

  # Must come after has_many association
  accepts_nested_attributes_for :guests, reject_if: proc { |attributes| attributes[:first_name].blank? && attributes[:last_name].blank? }

  # Validations
  #----------------------------------------------------------------------

  validates :name, presence: true

  # Methods
  #----------------------------------------------------------------------

  def has_address?
    !mailing_address.blank?
  end

  # Cleanup before saving
  def mailing_address=(val)
    self[:mailing_address] = val.strip
  end

  private

  def append_party_to_name
    if !name.to_s.strip.downcase.ends_with?("party")
      self[:name] = "#{name.to_s.strip} Party"
    end
  end
end

app/controllers/authenticated/base_controller.rb
#======================================================================
# Parent for any controllers that require an authenticated user.
#======================================================================
module Authenticated
  class BaseController < ::ApplicationController
    layout "application"
    before_action :require_user

    def current_user
      if cookies[:user_authentication_token]
        @current_user ||= User.includes(:account).find_by(authentication_token: cookies[:user_authentication_token])
      end
    end
    helper_method :current_user

    def current_account
      if current_user
        @current_account ||= current_user.account
      end
    end
    helper_method :current_account

    private

    def require_user
      destroy_session_for_user("Must login before continuing") unless current_user.present?
    end

    def require_account_owner
      destroy_session_for_user("Account Owner required for that action") unless current_user.present? && current_user.account_owner?
    end
  end
end

app/controllers/authenticated/dashboards_controller.rb
module Authenticated
  class DashboardsController < BaseController
    before_action :set_page_title

    def show
      @attending = current_account.guests.attending.alphabetical.includes(:party)
      @not_attending = current_account.guests.not_attending.alphabetical.includes(:party)
      @not_rsvped = current_account.guests.not_rsvped.alphabetical.includes(:party)
    end

    private

    def set_page_title
      @page_title = "Dashboard"
    end
  end
end

app/controllers/authenticated/guests_controller.rb
module Authenticated
  class GuestsController < BaseController
    def index
      # @parties = current_account.parties.includes(:guests).alphabetical
      # @guests = current_account.guests.includes(:party).alphabetical
    end

    def new
      @party = get_party
      @guest = @party.guests.new
    end

    def create
      @party = get_party
      @guest = @party.guests.new(guest_params)
      if @guest.save
        flash[:notice] = "Guest created"
        redirect_to new_party_guest_path(@party.uuid)
      else
        flash[:error] = "Problem adding Guest"
        render :new
      end
    end

    def show
      @party = get_party
      @guest = get_guest
    end

    def edit
      @party = get_party
      @guest = get_guest
    end

    def update
      @party = get_party
      @guest = get_guest
      if @guest.update_attributes(guest_params)
        flash[:notice] = "Updated Guest"
        redirect_to party_path(@party.uuid)
      else
        flash[:error] = "Problem updating Guest"
        render :edit
      end
    end

    def destroy
      @party = get_party
      @guest = get_guest

      if @guest.destroy
        flash[:notice] = "Removed Guest"
        redirect_to party_path(@party.uuid)
      else
        flash[:error] = "Problem deleting Guest"
        render :show
      end
    end

    private

    def guest_params
      params.require(:guest).permit(
        :first_name,
        :last_name,
        :notes,
        :attending,
        alcoholic_beverage_ids: []
      ).merge(account: current_account)
    end

    def get_party
      @party ||= current_account.parties.find_by(uuid: params[:party_uuid])
    end

    def get_guest
      @guest ||= get_party.guests.find_by(uuid: params[:uuid])
    end
  end
end

app/controllers/authenticated/invitations_controller.rb
module Authenticated
  class InvitationsController < BaseController
    before_action :set_page_title

    def index
      @parties = current_account.parties.invitation_not_sent.alphabetical.group_by { |p| p.name.first.upcase }
    end

    def update
      @party = get_party
      if @party.update_attributes(party_params)
        flash.now[:notice] = "Updated Party"
      else
        # NOOP
      end
    end

    private

    def get_party
      current_account.parties.find_by(uuid: params[:uuid])
    end

    def party_params
      params.require(:party).permit(
        :invitation_sent
      )
    end

    def set_page_title
      @page_title = "Invitations not Sent"
    end
  end
end

app/controllers/authenticated/mailing_addresses_controller.rb
module Authenticated
  class MailingAddressesController < BaseController
    def index
      @parties = current_account.parties.missing_mailing_address.alphabetical.group_by { |p| p.name.first.upcase }
    end

    def update
      @party = get_party
      if @party.update_attributes(party_params)
        flash.now[:notice] = "Updated Mailing Address"
      else
        # NOOP
      end
    end

    private

    def get_party
      current_account.parties.find_by(uuid: params[:uuid])
    end

    def party_params
      params.require(:party).permit(
        :mailing_address
      )
    end
  end
end

app/controllers/authenticated/missing_mailing_addresses_controller.rb
module Authenticated
  class MissingMailingAddressesController < BaseController
    before_action :set_page_title

    def index
      @parties = current_account.parties.missing_mailing_address.alphabetical.group_by { |p| p.name.first.upcase }
    end

    def update
      @party = get_party
      if @party.update_attributes(party_params)
        flash.now[:notice] = "Updated Mailing Address"
      else
        # NOOP
      end
    end

    private

    def get_party
      current_account.parties.find_by(uuid: params[:uuid])
    end

    def party_params
      params.require(:party).permit(
        :mailing_address
      )
    end

    def set_page_title
      @page_title = "Missing Addresses"
    end
  end
end

app/controllers/authenticated/parties_controller.rb
module Authenticated
  class PartiesController < BaseController
    def index
      @parties = current_account.parties.includes(:guests).alphabetical.group_by { |p| p.name.first.upcase }
    end

    def new
      @party = current_account.parties.new
      3.times { @party.guests.build }
      @guests = @party.guests
    end

    def build_guest
    end

    def create
      @party = current_account.parties.new(party_params)
      if @party.save
        flash[:notice] = "Created Party"
        redirect_to new_party_guest_path(@party.uuid)
      else
        flash[:error] = "Problem adding Party"
        render :new
      end
    end

    def show
      @party = get_party
    end

    def edit
      @party = get_party
      @guests = @party.guests.alphabetical
    end

    def update
      @party = get_party

      respond_to do |format|
        if @party.update_attributes(party_params)
          format.html { redirect_to party_path(@party.uuid), notice: "Updated Party" }
          format.js { flash.now[:notice] = "Updated Party" }
        else
          format.html do
            flash[:error] = "Problem updating Party"
            render :edit
          end
          format.js { flash.now[:error] = "Problem updating Party" }
        end
      end
    end

    def destroy
      @party = get_party

      if @party.destroy
        flash[:notice] = "Removed Party"
        redirect_to parties_path
      else
        flash[:error] = "Problem deleting Party"
        render :show
      end
    end

    private

    def party_params
      params.require(:party).permit(
        :name,
        :save_the_date_sent,
        :invitation_sent,
        :mailing_address,
        :address1,
        :address2,
        :city,
        :state,
        :zip,
        guests_attributes: [:id, :first_name, :last_name, alcoholic_beverage_ids: []]
      )
    end

    def get_party
      current_account.parties.find_by(uuid: params[:uuid])
    end
  end
end

app/controllers/authenticated/save_the_dates_controller.rb
module Authenticated
  class SaveTheDatesController < BaseController
    before_action :set_page_title

    def index
      @parties = current_account.parties.save_the_date_not_sent.alphabetical.group_by { |p| p.name.first.upcase }
    end

    def update
      @party = get_party
      if @party.update_attributes(party_params)
        flash.now[:notice] = "Updated Party"
      else
        # NOOP
      end
    end

    private

    def get_party
      current_account.parties.find_by(uuid: params[:uuid])
    end

    def party_params
      params.require(:party).permit(
        :save_the_date_sent
      )
    end

    def set_page_title
      @page_title = "Save the Dates not Sent"
    end
  end
end

app/controllers/authenticated/users_controller.rb
module Authenticated
  class UsersController < BaseController
    before_action :require_account_owner, except: [:index, :show]

    def index
      @invited_users = current_account.users.unconfirmed.alphabetical
      @users = current_account.users.confirmed.alphabetical
    end

    def new
      @user = current_account.users.new
    end

    def create
      @user = ::Users::AsInvitation.new(invitation_params.merge(account: current_account))
      if @user.save
        flash[:notice] = "Invitation sent"
        redirect_to users_path
      else
        flash[:error] = "Problem inviting user"
        render :new
      end
    end

    def show
      @user = get_user
    end

    def edit
      @user = get_user
    end

    def update
      @user = get_user
      if @user.update_attributes(user_params)
        flash[:notice] = "Updated User"
        redirect_to user_path(@user.uuid)
      else
        flash[:error] = "Problem updating User"
        render :edit
      end
    end

    def destroy
      @user = get_user

      if @user.account_owner?
        flash[:error] = "Cannot remove Account Owner"
        redirect_to users_path
      else
        if @user.destroy
          flash[:notice] = "Removed User"
          redirect_to users_path
        else
          flash[:error] = "Problem deleting User"
          render :show
        end
      end
    end

    private

    def invitation_params
      params.require(:user).permit(
        :full_name,
        :email
      )
    end

    def user_params
      params.require(:user).permit(
        :email,
        :full_name
      )
    end

    def get_user
      current_account.users.find_by(uuid: params[:id])
    end
  end
end

app/views/authenticated/parties/_blank_state.html.erb
<div class="blank-state-container">
  <div class="blank-state">
    <div class="blank-state-primary">
      No Parties/Guests Yet
      <div class="blank-state-primary-subtext">
        A Party is a group of associated Guests that
        usually share the same mailing address.
      </div>
    </div>
    <div class="blank-state-actions">
      <%= link_to "Add Your First Party", new_party_path, class: "button button-outline-primary" %>
    </div>
  </div>
</div>

app/views/authenticated/parties/_destroy_confirm_template.html.erb
<script id="party-confirm-dialog-template" type="text/x-handlebars-template">
  <header>
    <div class="dialog-title">Remove Party?</div>
  </header>
  <div class="dialog-content">
    Do you want to <strong class="color-red">completely</strong> remove this Party?

    <ul class="helper-text">
      <li>All Guests in this Party will be removed</li>
      <li>All information about this Party will be lost</li>
    </ul>
  </div>
  <div class="dialog-actions align-right">
    <button type="button" class="button button-flat-grey" role="cancel">Cancel</button>
    <button type="button" class="button button-flat-red" role="confirm">Remove</button>
  </div>
</script>

app/views/authenticated/parties/_fields.html.erb
<div class="card-header no-border-bottom">
  <div class="card-header-primary">
    <div class="field-with-validations text-field-underline-container">
      <%= f.text_field :name, class: "full-width font-size-large", autofocus: true, required: true, placeholder: "Party Name" %>
      <div class="helper-text helper-text-bottom">
        The word "Party" will automatically be added at the end for you
      </div>
      <%= bottom_error_messages_helper @party, :name %>
    </div>
  </div>
</div>
<div class="list list-hoverable">
  <label for="party_save_the_date_sent" class="list-item">
    <div class="list-item-primary">
      <%= f.label :save_the_date_sent, "Save the Date Sent?" %>
    </div>
    <div class="list-item-secondary">
      <div class="switch switch-primary">
        <%= f.check_box :save_the_date_sent %>
        <label for="party_save_the_date_sent"></label>
      </div>
    </div>
  </label>
  <label for="party_invitation_sent" class="list-item">
    <div class="list-item-primary">
      <%= f.label :invitation_sent, "Invitation Sent?" %>
    </div>
    <div class="list-item-secondary">
      <div class="switch switch-primary">
        <%= f.check_box :invitation_sent %>
        <label for="party_invitation_sent"></label>
      </div>
    </div>
  </label>
</div>
<div class="card-content">
  <div class="field-title">
    Mailing Address
  </div>
  <div class="field field-xsmall">
    <%= f.text_area :mailing_address, class: "full-width", rows: 4 %>
  </div>
</div>

app/views/authenticated/parties/_guest_form.html.erb
<div class="card full-width">
  <div class="card-header background-color-hover">
    <div class="card-header-primary font-size-normal">
      Guests in Party
    </div>
  </div>
  <div class="card-content">
    <%= f.fields_for :guests, @guests do |guest_form| %>
      <div class="field field-xsmall">
        <div class="field-element">
          <%= guest_form.text_field :first_name, size: 8 %>
          <%= guest_form.text_field :last_name, size: 12 %>
        </div>
      </div>
      <div class="field field-xsmall">
        <div class="field-element">
          <%= guest_form.collection_check_boxes(:alcoholic_beverage_ids, AlcoholicBeverage.alphabetical, :id, :name) do |b| %>
            <div class="checkbox">
              <%= b.check_box %> <%= b.label %>
            </div>
          <% end %>
        </div>
      </div>

      <hr class="divider normal" />
    <% end %>
    <div class="">
      <%= f.submit "Update", class: "button button-raised-primary", id: "update-party-button" %>
      <%= link_to "Cancel", parties_path, class: "button button-flat-grey" %>
    </div>
  </div>
</div>

app/views/authenticated/parties/_party.html.erb
<%= link_to party_path(party.uuid), class: "list-item", role: "party" do %>
  <div class="list-item-primary">
    <strong><%= party.name %></strong>
    <div class="list-item-primary-subtext">
      <%= pluralize party.guests.count, "Guest" %>
    </div>
  </div>
  <div class="list-item-secondary">
    <i class="material-icons color-<%= party.save_the_date_sent? ? 'icon' : 'divider' %>" title="Save the Date Sent">email</i>
    <i class="material-icons color-<%= party.invitation_sent? ? 'icon' : 'divider' %>" title="Invitation Sent">email</i>
    <i class="material-icons color-<%= party.has_address? ? 'icon' : 'divider' %>" title="Mailing Address">place</i>
  </div>
<% end %>

app/views/authenticated/parties/edit.html.erb
<% content_for(:appbar_nav_icon) { up_button(party_path(@party.uuid)) } %>
<% content_for(:appbar_title) { "Edit Party" } %>
<% content_for(:appbar_actions) do %>
  <%= button_tag "Update", class: "button button-raised-white", data: { submit: "#party-form" } %>
<% end %>

<%= form_for @party, url: party_path(@party.uuid), html: { id: "party-form" } do |f| %>
  <div class="card constrained-medium">
    <%= render "authenticated/parties/fields", f: f %>
    <div class="card-actions">
      <%= f.submit "Update", class: "button button-raised-primary", id: "update-party-button" %>
      <%= link_to "Cancel", party_path(@party.uuid), class: "button button-flat-grey" %>
    </div>
  </div>
<% end %>

app/views/authenticated/parties/index.html.erb
<% title "All Parties" %>
<% content_for(:appbar_actions) do %>
  <%= link_to "add", new_party_path, class: "material-icons appbar-button", tooltip: "Invite User", id: "new-user-button", data: { tooltip: "New" } %>
<% end %>

<%= link_to new_party_path, class: "button fab fab-secondary", id: "new-guest-fab", data: { "tooltip-position": "left", tooltip: "New" }, role: "fab" do %>
  <i class="material-icons">add</i>
<% end %>

<% if @parties.any? %>
  <div class="list-subheader">
    A Party is a group of associated Guests
  </div>
  <div class="list list-hoverable list-bordered list-two-lines list-divided rounded-corners background-color-white allow-room-for-fab-at-bottom" id="parties">
    <% @parties.each do |letter, parties| %>
      <div class="list-header">
        <div class="list-header-primary">
          <%= letter %>
        </div>
      </div>
      <%= render parties %>
    <% end %>
  </div>
<% else %>
  <%= render "authenticated/parties/blank_state" %>
<% end %>

app/views/authenticated/parties/new.html.erb
<% content_for(:appbar_nav_icon) do %>
  <%= link_to "arrow_back", parties_path, class: "material-icons appbar-button" %>
<% end %>
<% content_for(:appbar_title) { "New Party" } %>
<% content_for(:appbar_actions) do %>
  <%= button_tag "Create", class: "button button-raised-white", data: { submit: "#party-form" } %>
<% end %>

<%= form_for @party, url: parties_path, html: { id: "party-form" } do |f| %>
  <div class="card constrained-medium">
    <%= render "authenticated/parties/fields", f: f %>
    <div class="card-actions">
      <%= f.submit "Create", class: "button button-raised-primary", id: "create-party-button" %>
      <%= link_to "Cancel", parties_path, class: "button button-flat-grey" %>
    </div>
  </div>
<% end %>

app/views/authenticated/parties/show.html.erb
<% content_for(:appbar_nav_icon) { up_button(parties_path) } %>
<% content_for(:appbar_title) { "Party" } %>
<% content_for(:appbar_actions) do %>
  <%= link_to "edit", edit_party_path(@party.uuid), class: "material-icons appbar-button", data: { tooltip: "Edit" } %>
  <span class="menu-container">
    <i class="material-icons appbar-button" role="menu-trigger" data-menu-id="appbar-menu">more_vert</i>
    <div class="menu menu-width-2" id="appbar-menu" data-position="top-right">
      <%= link_to party_path(@party.uuid), method: "DELETE", class: "menu-item", id: "delete-party-link", data: { "custom-confirm" => { template: "party-confirm-dialog-template" } } do %>
        <div class="menu-item-icon">
          <i class="material-icons">delete</i>
        </div>
        <div class="menu-item-primary">
          Remove Party
        </div>
      <% end %>
    </div>
  </span>
<% end %>

<%= link_to new_party_guest_path(@party.uuid), class: "button fab fab-secondary", id: "new-guest-fab", data: { "tooltip-position": "left", tooltip: "Add Guests" }, role: "fab" do %>
  <i class="material-icons">person_add</i>
<% end %>

<div class="card constrained-medium">
  <div class="card-header no-border-bottome">
    <div class="card-header-primary">
      <%= @party.name %>
    </div>
  </div>
  <!-- Fields use auto-submit so cannot use same as new/edit forms -->
  <%= form_for @party, url: party_path(@party.uuid), html: { id: "party-form" }, remote: true do |f| %>
    <div class="list list-hoverable">
      <label for="party_save_the_date_sent" class="list-item">
        <div class="list-item-primary">
          <%= f.label :save_the_date_sent, "Save the Date Sent?" %>
        </div>
        <div class="list-item-secondary">
          <div class="switch switch-primary">
            <%= f.check_box :save_the_date_sent, data: { "auto-submit-on-change" => true } %>
            <label for="party_save_the_date_sent"></label>
          </div>
        </div>
      </label>
      <label for="party_invitation_sent" class="list-item">
        <div class="list-item-primary">
          <%= f.label :invitation_sent, "Invitation Sent?" %>
        </div>
        <div class="list-item-secondary">
          <div class="switch switch-primary">
            <%= f.check_box :invitation_sent, data: { "auto-submit-on-change" => true } %>
            <label for="party_invitation_sent"></label>
          </div>
        </div>
      </label>
    </div>
  <% end %>
  <div class="card-content">
    <div class="field-title flex-parent-row">
      Mailing Address
    </div>
    <% if @party.has_address? %>
      <%= simple_format @party.mailing_address, {}, { wrapper_tag: "div" } %>
    <% else %>
      <div class="helper-text">
        No Address
      </div>
    <% end %>
  </div>
</div>

<hr class="spacer small" />

<div class="card constrained-medium allow-room-for-fab-at-bottom">
  <div class="card-header background-color-hover">
    <div class="card-header-primary">
      Guests
    </div>
  </div>
  <% if @party.guests.any? %>
    <div class="list list-divided list-two-lines" id="guests">
      <% if @party.guests.attending.any? %>
        <div class="list-header">
          <div class="list-header-primary">
            <%= @party.guests.attending.count %> Attending
          </div>
        </div>
        <%= render @party.guests.attending.alphabetical %>
      <% end %>
      <% if @party.guests.not_attending.any? %>
        <div class="list-header">
          <div class="list-header-primary">
            <%= @party.guests.not_attending.count %> Not Attending
          </div>
        </div>
        <%= render @party.guests.not_attending.alphabetical %>
      <% end %>
    </div>
  <% else %>
    <div class="list list-hoverable list-one-lines" id="guests">
      <%= link_to new_party_guest_path(@party.uuid), class: "list-item list-item-hoverable" do %>
        <div class="list-item-icon">
          <i class="material-icons">add</i>
        </div>
        <div class="list-item-primary">
          Add First Guest
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/authenticated/parties/update.js.erb
App.MD.Snackbar.create("<%= flash.now[:notice] %>");